if [ "$TMUX" = "" ]; then tmux; fi

# Enable gpg-agent if it is not running
GPG_AGENT_SOCKET="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"
if [ ! -S $GPG_AGENT_SOCKET ]; then
  gpg-agent --daemon >/dev/null 2>&1
  export GPG_TTY=$(tty)
fi

# Set SSH to use gpg-agent if it is configured to do so
GNUPGCONFIG=${GNUPGHOME:-"$HOME/.gnupg/gpg-agent.conf"}
if [ -r "$GNUPGCONFIG" ] && grep -q enable-ssh-support "$GNUPGCONFIG"; then
  unset SSH_AGENT_PID
  export SSH_AUTH_SOCK=$GPG_AGENT_SOCKET
fi

ZSH=$HOME/.oh-my-zsh
ZSH_THEME="brancz"

if [[ "$OSTYPE" == linux* ]]; then
  alias open="gnome-open"
fi
alias vi="vim"
alias r="ranger"
alias cb="xclip -selection c -i"

plugins=(git)

source $ZSH/oh-my-zsh.sh
alias ls="ls -G --color=auto"

export EC2_HOME=/usr/local/ec2
export GOPATH=$HOME/go

export PATH=$PATH:$EC2_HOME/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$JAVA_HOME/bin
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/usr/local/apiserver-builder/bin
export PATH=$PATH:$HOME/.cargo/bin

function resetdocker() {
  unset DOCKER_TLS_VERIFY
  unset DOCKER_HOST
  unset DOCKER_CERT_PATH
  unset DOCKER_API_VERSION
}
