if [ "$TMUX" = "" ]; then tmux; fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="flower-pot"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias sr="screen -r"
if [[ "$OSTYPE" == linux* ]]; then
  alias open="gnome-open"
fi
alias vi="vim"
alias wow="git status"
alias such="git"
alias much="git"
alias very="git"
alias r="ranger"
if [[ "$OSTYPE" == linux* ]]; then
  alias cb="xclip -selection c -i"
fi
if [[ "$OSTYPE" == darwin* ]]; then
  alias cb="pbcopy"
  export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"
fi
alias cbssh="cat ~/.ssh/id_rsa.pub | cb"
alias cbwd="pwd | cb"
alias docs="zeal --query $1 &"
alias tmux="tmux -2"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh
alias ls="ls -G --color=auto"

# Customize to your needs...

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$PATH:$HOME/bin # Add ~/bin to PATH

# added by travis gem
[ -f /home/flower-pot/.travis/travis.sh ] && source /home/flower-pot/.travis/travis.sh

export PYTHONDONTWRITEBYTECODE=true

EC2_HOME=/usr/local/ec2
PATH=$PATH:$EC2_HOME/bin

if [[ "$OSTYPE" == darwin* ]]; then

  JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/
fi
PATH=$PATH:$JAVA_HOME/bin

export GOPATH=$HOME/go

export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export PATH=$PATH:/usr/local/sbin

# added by travis gem
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh

function resetdocker() {
  unset DOCKER_TLS_VERIFY
  unset DOCKER_HOST
  unset DOCKER_CERT_PATH
  unset DOCKER_API_VERSION
}

function dockertag() {
  version=$(git describe --abbrev=0)
  buildmetadata=$(git rev-parse --abbrev-ref HEAD)
}

PATH=$PATH:/usr/local/apiserver-builder/bin
