if [ "$TMUX" = "" ]; then tmux; fi

export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

ZSH=$HOME/.oh-my-zsh
ZSH_THEME="brancz"

if [[ "$OSTYPE" == linux* ]]; then
  alias open="gnome-open"
fi
alias r="ranger"
alias cb="xclip -selection c -i"

plugins=(git pass)

source $ZSH/oh-my-zsh.sh
alias ls="ls -G --color=auto"

export EC2_HOME=/usr/local/ec2
export GOPATH=$HOME
export GOBIN=$HOME/bin

export PATH=$PATH:$EC2_HOME/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$JAVA_HOME/bin
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/usr/local/apiserver-builder/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/.tiup/bin
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

function resetdocker() {
  unset DOCKER_TLS_VERIFY
  unset DOCKER_HOST
  unset DOCKER_CERT_PATH
  unset DOCKER_API_VERSION
}

PATH="/home/brancz/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/brancz/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/brancz/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/brancz/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/brancz/perl5"; export PERL_MM_OPT;

export PATH="$HOME/.yarn/bin:$PATH"

autoload -U compinit; compinit

# Check if 'kubectl' is a command in $PATH
if [ $commands[kubectl] ]; then

  # Placeholder 'kubectl' shell function:
  # Will only be executed on the first call to 'kubectl'
  kubectl() {

    # Remove this function, subsequent calls will execute 'kubectl' directly
    unfunction "$0"

    # Load auto-completion
    source <(kubectl completion zsh)

    # Execute 'kubectl' binary
    $0 "$@"
  }
fi

# Check if 'podman' is a command in $PATH
if [ $commands[podman] ]; then

  # Placeholder 'podman' shell function:
  # Will only be executed on the first call to 'podman'
  podman() {

    # Remove this function, subsequent calls will execute 'podman' directly
    unfunction "$0"

    # Load auto-completion
    source <(podman completion zsh)

    # Execute 'podman' binary
    $0 "$@"
  }
fi

export PATH=$PATH:$HOME/.linkerd2/bin
export EDITOR="nvim"

source $HOME/.profile

export PATH=/home/brancz/.tiup/bin:$PATH

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/brancz/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/brancz/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/brancz/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/brancz/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

export PATH=$PWD/bin:$PATH

export USE_GKE_GCLOUD_AUTH_PLUGIN=True
export PATH="/opt/homebrew/opt/binutils/bin:$PATH"
export PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"
#export PATH="/Users/brancz/src/go.googlesource.com/go/bin:$PATH"
